- name: roboshop instances management
  hosts: local
  connection: local
  vars:
    instances: ["mongodb", "redis", "mysql", "rabbitmq", "catalogue", "user", "cart", "shipping", "payment", "frontend"]
    image_id: ami-0220d79f3f480ecf5
    domain_name: daws90s.shop # replace with your domain
    action: create
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t3.micro
      name: "roboshop-{{ item }}"
      image_id: "{{ image_id }}"
      region: us-east-1
      security_groups:
      - "roboshop-{{ item }}"
      - roboshop-common
    loop: "{{ instances }}"
    register: ec2_output
    when: action == "create"

  # - name: print output
  #   debug:
  #     msg: "{{ ec2_output }}"

  # - name: create route53 record
  #   debug:
  #     msg: "Instance Name: {{ item.item }} PrivateIP: {{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" #mongodb.daws90s.shop
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: action == "create"
    
  - name: create r53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ domain_name }}" #daws90s.shop
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: 
    - item.item == "frontend" 
    - action == "create"

  - name: delete r53 records
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ item }}.{{ domain_name }}" # mongodb.daws90s.shop
      ttl: 1
      type: A
    loop: "{{ instances  }}"  
    when: action == "delete"

  - name: delete r53 record for frontend
    amazon.aws.route53:
      state: absent
      zone: "{{ domain_name }}"
      record: "{{ domain_name }}" # daws90s.shop
      ttl: 1
      type: A
    loop: "{{ instances  }}"  
    when: 
    - action == "delete"
    - item == "frontend"
  
  - name: delete ec2 instances
    amazon.aws.ec2_instance:
      state: absent
      name: "roboshop-{{ item }}"
      wait: false
    loop: "{{ instances  }}"  
    when: action == "delete"