- name: app setup
  import_role:
    name: common
    tasks_from: app-setup

- name: python setup
  import_role:
    name: common
    tasks_from: python

- name: systemd setup
  import_role:
    name: common
    tasks_from: systemd-setup

- name: restart
  import_role:
    name: common
    tasks_from: restart