MONGODB_HOST: mongodb-{{ env }}.vijaansh.online
REDIS_HOST: redis-{{ env }}.vijaansh.online
MYSQL_HOST: mysql-{{ env }}.vijaansh.online 
RABBITMQ_HOST: rabbitmq-{{ env }}.vijaansh.online 
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.vijaansh.online
USER_HOST: user.backend-alb-{{ env }}.vijaansh.online
CART_HOST: cart.backend-alb-{{ env }}.vijaansh.online
SHIPPING_HOST: shipping.backend-alb-{{ env }}.vijaansh.online
PAYMENT_HOST: payment.backend-alb-{{ env }}.vijaansh.online
