- name: copy rabbitmq repo
  copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
- name: install rabbitmq server
  package:
    name: rabbitmq-server
    state: present
- name: start and enable rabbitmq-server
  service:
    name: rabbitmq-server
    state: started
    enabled: yes
- name: create roboshop mq user
  community.rabbitmq.rabbitmq_user:
    user: "{{ MQ_USER }}"
    password: "{{ MQ_PASSWORD }}"
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present