# - name: get the password from AWS secrets manager
#   debug:
#     msg: "{{ lookup('amazon.aws.aws_secret', 'roboshop/mysql_root_password', region='us-east-1') | from_json  }}"

# - name: print root password
#   debug:
#     msg: "{{ root_password.mysql_root_password }}"
- name: install mysql server
  package:
    name: mysql-server
    state: present
- name: install boto3 botocore
  pip:
    name:
    - boto3
    - botocore
    executable: pip3.9
- name: start and enable mysql server
  service:
    state: started
    enabled: yes
    name: mysqld
- name: setup root password
  #command: mysql_secure_installation --set-root-pass "{{ MYSQL_ROOT_PASSWORD }}"
  command: mysql_secure_installation --set-root-pass "{{ mysql_root_password }}"