- name: create roboshop system user
  user:
    name: roboshop
    system: true
    home: /app
    shell: /sbin/nologin
    comment: "Roboshop System user"

- name: remove app directory
  file:
    path: /app
    state: absent

- name: "delete {{ component }}.zip in tmp directory"
  file:
    path: "/tmp/{{ component }}.zip"
    state: absent

- name: create app directory
  file:
    path: /app
    state: directory

- name: "download {{ component }}"
  get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-{{ app_version }}.zip"
    dest: "/tmp/{{ component }}.zip"

- name: "unzip {{ component }}"
  unarchive:
    src: "/tmp/{{ component }}.zip"
    dest: /app
    remote_src: yes
