- name: install maven
  package:
    name: maven
    state: present

- name: install dependencies
  command: mvn clean package
  args:
    chdir: /app
    
- name: move shipping jar
  command: mv target/shipping-1.0.jar shipping.jar 
  args:
    chdir: /app