- name: Demo Role
  debug:
    msg: "Hi, I am from Demo role tasks"
  # this should load another role called common
- name: import common role
  import_role:
    name: common
    tasks_from: hello.yaml
